name: AWS Resource Monitor

on:
  schedule:
    # runs daily at 6:00 UTC (adjust to your timezone)
    - cron: '0 6 * * *'
  workflow_dispatch:      # allows manual run

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Make script executable
        run: chmod +x scripts/aws_monitor.sh

      - name: Run AWS Monitor script
        id: monitor
        run: |
          scripts/aws_monitor.sh
        continue-on-error: false

      - name: Upload log artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: aws-monitor-log-${{ github.run_id }}
          path: scripts/aws_resource_report_*.log

      - name: Send email on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}   # probably your Gmail address
          password: ${{ secrets.SMTP_PASSWORD }}   # app password or SMTP password
          subject: AWS Monitor Alert - ${{ github.repository }}
          to: kumarbeckmanish@gmail.com
          from: AWS Monitor Bot <${{ secrets.SMTP_USERNAME }}>
          body: |
            The AWS Resource Monitor workflow failed. Please check the logs.
            View the artifact for more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

